if (window.location.href.match("https://www.ainex.com.br/5-passos-para-a-sua-primeira-importacao")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/234")) { window.location.href = "https://go.hotmart.com/F3001144M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/238")) { window.location.href = "https://go.hotmart.com/H9705758I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/239")) { window.location.href = "https://go.hotmart.com/J9121745W"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/23b")) { window.location.href = "https://go.hotmart.com/C18246365G"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/23c")) { window.location.href = "https://go.hotmart.com/O18246767Q"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/23d")) { window.location.href = "https://app.monetizze.com.br/r/AJH718997"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/23e")) { window.location.href = "https://app.monetizze.com.br/r/ALS5971264"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/23g")) { window.location.href = "https://go.hotmart.com/V19438950D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/23h")) { window.location.href = "https://go.hotmart.com/J7347588D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/como-criar-um-jornal-digital-em-sua-cidade")) { window.location.href = "https://go.hotmart.com/D12461310I?ap=39ac"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-crie-sites-de-video-em-piloto-automatico")) { window.location.href = "https://go.hotmart.com/A3004465M?ap=39ac"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/instalador-energia-solar")) { window.location.href = "https://go.hotmart.com/L7183690S"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/af-cursos-24-horas-online")) { window.location.href = "https://www.cursos24horas.com.br/parceiro.asp?cod=promocao107955"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-yoga-e-acao")) { window.location.href = "https://go.hotmart.com/X7973102I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/a-maquina-de-vendas-online")) { window.location.href = "https://go.hotmart.com/A10490692A"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/abrir-loterica")) { window.location.href = "https://go.hotmart.com/C3589944T"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/academia-do-importador")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/afiliado-a-ads")) { window.location.href = "https://a-ads.com/?partner=306499"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/afiliado-adf-ly")) { window.location.href = "https://join-adf.ly/9716799"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/afiliado-anunciad")) { window.location.href = "http://www.anunciad.com.br?u=32157"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/afiliado-organico")) { window.location.href = "https://go.hotmart.com/A3001198M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/afiliado-hostgator")) { window.location.href = "https://www.hostgator.com.br/20677.html"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/afiliados-imagem-folheados")) { window.location.href = "http://www.imagemfolheados.com.br/parceria/?a=86914"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/aliexpress-passo-a-passo")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/aprenda-desenhar-do-zero")) { window.location.href = "https://go.hotmart.com/I2938479M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/aprenda-importar-suplementos")) { window.location.href = "https://go.hotmart.com/X5287162Q"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/aumentar-score-bs")) { window.location.href = "https://app.monetizze.com.br/r/AYR1635369?src=blogspot"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/aumentar-score-yt")) { window.location.href = "https://app.monetizze.com.br/r/AYR1635369?src=youtube"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/bacharel-em-teologia")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/bacharel-teologia")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/biblia-capa-capa")) { window.location.href = "https://go.hotmart.com/C5716819X"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/box-anatomia-facil-curso-de-anatomia")) { window.location.href = "https://go.hotmart.com/E14279897E"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/canto-alem-da-voz")) { window.location.href = "https://go.hotmart.com/B7368341I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/cha-para-diabetes")) { window.location.href = "https://app.monetizze.com.br/r/AGM800732"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/como-cuidar-de-bonsai")) { window.location.href = "https://app.monetizze.com.br/r/AUU953700"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/como-ganhar-ainda-mais-com-o-seu-salao-de-beleza")) { window.location.href = "https://go.hotmart.com/O5209957G"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/como-importar-tenis")) { window.location.href = "https://go.hotmart.com/K5287150P"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/como-perder-barriga-em-30-dias")) { window.location.href = "https://go.hotmart.com/U10272009C"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/como-produzir-bacons-defumados-artesanais")) { window.location.href = "https://go.hotmart.com/U9432198I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/como-produzir-linguicas-artesanais")) { window.location.href = "https://go.hotmart.com/U9432198I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/criar-videos-animados")) { window.location.href = "https://go.hotmart.com/I7084848U"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/crie-sites-premium")) { window.location.href = "https://go.hotmart.com/K5382949D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-7-passos-para-transformar-sua-realidade")) { window.location.href = "https://go.hotmart.com/V7099140Y"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-a-formula-do-tcc-nota-10")) { window.location.href = "https://go.hotmart.com/O7313861T"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-aprenda-ganhar-dinheiro-e-investir-em-lotericas")) { window.location.href = "https://go.hotmart.com/Y4767243N"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-cara-da-foto")) { window.location.href = "https://go.hotmart.com/D7352139S"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/meu-dinheiro-perdido-faca-uma-busca")) { window.location.href = "https://go.hotmart.com/X7409646B"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-completo-de-capelania")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-conserto-de-celular")) { window.location.href = "https://go.hotmart.com/L14305080X"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-criar-site-profissional")) { window.location.href = "https://go.hotmart.com/A5290365R"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-bacharel-em-teologia")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-ciencias-da-religiao")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-comandos-eletricos")) { window.location.href = "https://go.hotmart.com/Y7347823J"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-criopeeling-ou-neve-carbonica")) { window.location.href = "https://go.hotmart.com/O7879506Y"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-depilacao-avancado")) { window.location.href = "https://go.hotmart.com/E5209945L"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-desenho-kero-desenhar")) { window.location.href = "https://go.hotmart.com/N7314375R"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-desenho-metodo-fanart-2-0")) { window.location.href = "https://go.hotmart.com/H9705758I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-doutor-em-teologia")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-eletronica-geral")) { window.location.href = "https://go.hotmart.com/B7460556X"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-ingles-basico-ingles-toda-hora")) { window.location.href = "https://go.hotmart.com/H5306373Q"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-ingles-propulsao-para-fluencia-3-0")) { window.location.href = "https://go.hotmart.com/M5306372Y"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-maquiagem-artistica")) { window.location.href = "https://go.hotmart.com/I4928943O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-maquiagem-da-juliana-goes")) { window.location.href = "https://go.hotmart.com/M5085367G"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-maquiagem-make-total")) { window.location.href = "https://go.hotmart.com/M5085367G"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-maquiagem-makeme-cosmetics")) { window.location.href = "https://go.hotmart.com/R4805375D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-maquiagem-para-olhos")) { window.location.href = "https://go.hotmart.com/A5166248S"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-maquiagem-para-pele-negra")) { window.location.href = "https://go.hotmart.com/V14279414X"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-memorizacao-da-biblia-memo-bible-3000")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-mestre-em-teologia")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-penteado-online")) { window.location.href = "https://go.hotmart.com/U3615855M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-preparacao-de-obreiros-diaconos-e-presbiteros-cpodp")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-retrospectiva-animada-de-casamento-e-aniversario")) { window.location.href = "https://go.hotmart.com/D1153904M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-teclado-online")) { window.location.href = "https://go.hotmart.com/Y8247012K"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-teologia-basico-medio")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-teologia-express")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-unhas-profissional-escola-das-unhas")) { window.location.href = "https://go.hotmart.com/A2979318M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-violao-gospel")) { window.location.href = "https://go.hotmart.com/A7411977V"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-wordpress")) { window.location.href = "https://go.hotmart.com/A5290365R"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-de-wordpress-optimizepress-expert-digital")) { window.location.href = "https://go.hotmart.com/U5290362Y"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-doutor-em-teologia")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-eliminar-acne")) { window.location.href = "https://go.hotmart.com/P4619028G"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-eliminar-calvicie")) { window.location.href = "http://mon.net.br/27jkq"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-em-video-lucrando-com-salgados")) { window.location.href = "https://go.hotmart.com/I7349246G"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-escola-de-negocios-online-2-0")) { window.location.href = "https://go.hotmart.com/O7409733Q"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-especial-ovos-de-pascoa")) { window.location.href = "https://go.hotmart.com/U7356154J"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-espetinho-gourmet")) { window.location.href = "https://go.hotmart.com/U9432198I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-ingles-em-24-horas")) { window.location.href = "https://go.hotmart.com/O4380771D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-ingles-em-24-horas-guia-de-sobrevivencia-para-quem-precisa-falar-ingles-urgente")) { window.location.href = "https://go.hotmart.com/O4380771D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-ingles-para-negocios-business-english")) { window.location.href = "https://go.hotmart.com/P5306343E"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-mecanico-de-automovel-completo")) { window.location.href = "https://go.hotmart.com/I7361323W"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-mestre-do-espetinho")) { window.location.href = "https://go.hotmart.com/U9432198I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-metodo-aprenda-importar-facilmente")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-online-formula-oab")) { window.location.href = "https://go.hotmart.com/L14280011T"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-online-sites-hmtl5-profissionais-com-wordpress-10-horas")) { window.location.href = "https://go.hotmart.com/A5290365R"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-pacotao-de-teologia")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-pacotao-de-teologia")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-porcelanato")) { window.location.href = "https://go.hotmart.com/J7347588D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-propulsao-para-fluencia-essential")) { window.location.href = "https://go.hotmart.com/E5306370U"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-segredos-da-importacao")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-segredos-da-taci")) { window.location.href = "https://go.hotmart.com/J5012924O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-trabalhar-pela-internet-agora")) { window.location.href = "https://go.hotmart.com/A3001198M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-violao-para-todos")) { window.location.href = "https://go.hotmart.com/A7411977V"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-youtube-diamante")) { window.location.href = "https://go.hotmart.com/L7494684I"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/curso-youtube-pro")) { window.location.href = "https://go.hotmart.com/V7906812F"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/detox-sem-segredos")) { window.location.href = "https://go.hotmart.com/X7092466A"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/dieta-de-4-semanas")) { window.location.href = "https://go.hotmart.com/U10272009C"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/dieta-nua-crua-e-gostosa-receitas-simples-para-emagrecer-com-saude")) { window.location.href = "https://go.hotmart.com/Q4619062D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/educafit-cursos-online")) { window.location.href = "https://go.hotmart.com/G7308316D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/em-forma-em-10")) { window.location.href = "https://go.hotmart.com/U10272009C"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/emagrecer-para-sempre")) { window.location.href = "https://go.hotmart.com/U10272009C"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/fabrica-de-lacos-e-tiaras")) { window.location.href = "https://go.hotmart.com/G7356092S"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/faculdade-do-ingles")) { window.location.href = "https://go.hotmart.com/E5306370U"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/fazer-o-cachorro-parar-de-latir-imediatamente")) { window.location.href = "https://go.hotmart.com/H7919141Y"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/fera-da-importacao")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/formacao-de-professores-e-lideres-para-escola-biblica-dominical")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/formacao-de-professores-e-lideres-para-o-ministerio-infantil")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/formula-de-mixagem-de-audio")) { window.location.href = "https://go.hotmart.com/T7398788Y"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/formula-negocio-online")) { window.location.href = "https://go.hotmart.com/A3001198M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/formula-oab-yt")) { window.location.href = "https://go.hotmart.com/J7314592A"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/frances-autentico")) { window.location.href = "https://go.hotmart.com/P7314474A"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/futuro-importador")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/guia-completo-do-pregador-iniciante")) { window.location.href = "https://go.hotmart.com/E11232067H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/guia-de-alimentacao-para-diabetes")) { window.location.href = "https://go.hotmart.com/W14279997H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/guia-importe-suplementos")) { window.location.href = "https://go.hotmart.com/X5287162Q"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/hemorroida-nao")) { window.location.href = "https://go.hotmart.com/H7732081L"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/importacao-ultimate")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/importador-mestre-3-0")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/importando-o-meu-primeiro-aeromodelo")) { window.location.href = "https://go.hotmart.com/l3006006M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/importar-pecas")) { window.location.href = "https://go.hotmart.com/D5287163R"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/joias-importadas")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/kit-2000-ilustracoes-esbocos-e-sermoes")) { window.location.href = "https://go.hotmart.com/P5289271O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/kit-curso-pregador-completo")) { window.location.href = "https://go.hotmart.com/P5289271O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/kit-curso-pregador-completo-como-preparar-sermoes-e-pregar-a-biblia")) { window.location.href = "https://go.hotmart.com/P5289271O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/loja-beijo-pink-shop")) { window.location.href = "https://www.pinceisemaquiagem.com.br/?ref=60088"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/loja-imagem-folheados")) { window.location.href = "http://www.imagemfolheados.com.br/?a=86914"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/loja-intima-store")) { window.location.href = "https://www.intimastore.com.br/home.asp?IDLoja=5139&amp;origem=penteadodenoiva"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/loja-maquiadoro")) { window.location.href = "https://www.pinceisemaquiagem.com.br/?ref=60088"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/loja-progressiva-brasil")) { window.location.href = "https://www.pinceisemaquiagem.com.br/?ref=60088"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/loja-tudo-saudavel")) { window.location.href = "https://www.tudosaudavel.com/?afiliado=181"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/lover-amante-das-mulheres")) { window.location.href = "https://go.hotmart.com/A8597265K"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/manual-biblico-das-questoes-dificeis-e-polemicas-da-biblia")) { window.location.href = "https://go.hotmart.com/P5289271O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/maquina-de-vendas-usa")) { window.location.href = "https://go.hotmart.com/A10490692A"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/metodo-aprenda-importar-facilmente")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/metodo-como-ler-a-biblia-e-entende-la-mais-facilmente-30-edicao")) { window.location.href = "https://go.hotmart.com/K5289272V"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/metodo-da-libido")) { window.location.href = "https://go.hotmart.com/I7182295J"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/modo-assinatura-mensal-idioma-facil")) { window.location.href = "https://go.hotmart.com/J5306363D"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/monografis-orientador-tcc")) { window.location.href = "https://go.hotmart.com/O7313861T"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/ms-unhas-acrilicas")) { window.location.href = "https://go.hotmart.com/P7366424Y"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/o-poder-do-invisivel-curso-online-de-radiestesia")) { window.location.href = "https://go.hotmart.com/C7285076B"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/o-que-e-bitcoin-guia-definitivo-financas-e-investimentos")) { window.location.href = "https://go.hotmart.com/O6345552E"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/o-segredo-dos-ar-split-manutencao-ar-condicionado")) { window.location.href = "https://go.hotmart.com/C7349334V"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/olx-para-afiliados")) { window.location.href = "https://go.hotmart.com/E7347461V"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/orquideas-curso-completo-em-video")) { window.location.href = "https://go.hotmart.com/T6328512H"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/perca-peso-de-vez")) { window.location.href = "https://go.hotmart.com/U10272009C"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/poderosa-na-cama-prazeres-nao-convencionais")) { window.location.href = "https://go.hotmart.com/G3006387M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/produto-eliminar-acne")) { window.location.href = "https://go.hotmart.com/O7879506Y"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/programa-comprar-eua")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/programa-relacionamento-na-pratica")) { window.location.href = "https://go.hotmart.com/N7085563T"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/queima-de-gordura-abdominal")) { window.location.href = "https://go.hotmart.com/U7099464J"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/roupas-para-pet")) { window.location.href = "https://go.hotmart.com/K7440454B"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/sem-candidiase")) { window.location.href = "http://mon.net.br/1u6rk"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/socio-escola-da-prevencao-seguranca-do-trabalho")) { window.location.href = "https://go.hotmart.com/B7352292L"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/sucos-detox-desafio-21-dias")) { window.location.href = "https://go.hotmart.com/J7356141R"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/tesouro-direto")) { window.location.href = "https://go.hotmart.com/D14279869M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/trading-esportivo")) { window.location.href = "https://go.hotmart.com/J3004441M"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/treinamento-negocio-mobile")) { window.location.href = "https://go.hotmart.com/K7427095E"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/venda-samurai")) { window.location.href = "https://go.hotmart.com/Y7256569F"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/vendedor-online-internacional")) { window.location.href = "https://go.hotmart.com/V7265163O"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/verdadeiro-amante-tecnicas-de-seducao")) { window.location.href = "https://go.hotmart.com/A8597265K"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/violao-para-todos")) { window.location.href = "https://go.hotmart.com/A7411977V"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/viver-de-vendas-e-commerce-olx-mercado-livre")) { window.location.href = "https://go.hotmart.com/E7347461V"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/viver-melhor-agora")) { window.location.href = "https://go.hotmart.com/Q7475449S"; var link_afiliado = 1; } else 
if (window.location.href.match("https://www.ainex.com.br/wordpress-essencial-para-iniciantes")) { window.location.href = "https://go.hotmart.com/Q5306000R"; }
if (window.location.href.match("https://www.ainex.com.br/a-dieta-de-21-dias")) { window.location.href = "https://go.hotmart.com/U10272009C"; var link_afiliado = 1; }
